export const actionTypes = {
  ADD_PRODUCT_LIST: "ADD_PRODUCT_LIST",
  PRODUCT_DETAILS: "PRODUCT_DETAILS",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOE_PRODUCT_FROM_CART: "REMOE_PRODUCT_FROM_CART"
};
